# Generated by Django 2.0.7 on 2018-07-09 10:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cmc_id', models.IntegerField()),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('btc', models.DecimalField(decimal_places=10, max_digits=100)),
                ('usd', models.DecimalField(decimal_places=4, max_digits=100)),
                ('market_cap', models.DecimalField(decimal_places=1, max_digits=100)),
                ('daily_volume', models.IntegerField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctypto_price', to='market.CryptoCurrency')),
            ],
        ),
    ]
