# Generated by Django 2.0.7 on 2018-07-09 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20180709_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelisting',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
