# Generated by Django 2.0.7 on 2018-07-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_num', models.IntegerField(unique=True)),
                ('block_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
