# Generated by Django 2.0.7 on 2018-07-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='block_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
